title: Edgewit
description: A lightweight, Rust-based search and analytics engine for edge environments.

# GitHub Pages automatically configures url and baseurl,
# keeping them empty prevents accidental overrides.
baseurl: "/edgewit"
url: ""

github_username: viljami

# Using custom layouts in _layouts/default.html instead of a pre-built theme
# theme: minima

permalink: pretty

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
